# Generated by Django 2.2 on 2020-02-01 09:39

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=50)),
                ('password2', models.CharField(max_length=50)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Others')])),
                ('address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('user_img', models.ImageField(blank=True, null=True, upload_to='UserImg')),
                ('citizenship_img', models.ImageField(upload_to='Citizenship')),
                ('Liscence_img', models.ImageField(upload_to='LiscenceImg')),
                ('languages', multiselectfield.db.fields.MultiSelectField(choices=[('Nepali', 'Nepali'), ('English', 'English'), ('Spanish', 'Spanish'), ('Hindi', 'Hindi'), ('Chinese', 'Chinese')], max_length=36)),
                ('locations', multiselectfield.db.fields.MultiSelectField(choices=[('Kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur'), ('Everest Base Camp', 'Everest Base Camp'), ('Annapurna Base Camp', 'Annapurna Base Camp')], max_length=66)),
            ],
        ),
    ]
