# Generated by Django 2.2 on 2020-02-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterModel',
            new_name='GuideRegisterModel',
        ),
    ]
