# Generated by Django 2.2 on 2020-02-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20200201_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristRegisterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=50)),
                ('password2', models.CharField(max_length=50)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Others')])),
            ],
        ),
        migrations.AddField(
            model_name='guideregistermodel',
            name='bio_desc',
            field=models.TextField(default=0, max_length=225),
            preserve_default=False,
        ),
    ]
