# Generated by Django 2.2 on 2020-02-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20200201_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideregistermodel',
            name='is_guide',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='touristregistermodel',
            name='is_guide',
            field=models.BooleanField(default=False),
        ),
    ]
