# Generated by Django 2.2 on 2020-02-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20200201_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideregistermodel',
            name='is_guide',
        ),
        migrations.RemoveField(
            model_name='touristregistermodel',
            name='is_guide',
        ),
    ]
