# Generated by Django 2.2 on 2020-02-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_auto_20200201_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideregistermodel',
            name='is_guide',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='touristregistermodel',
            name='is_tourist',
            field=models.BooleanField(default=1),
        ),
    ]
