# Generated by Django 2.2 on 2020-02-11 17:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_auto_20200210_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideregistermodel',
            name='languages',
        ),
        migrations.AddField(
            model_name='guideregistermodel',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Nepali', 'Nepali'), ('English', 'English'), ('Spanish', 'Spanish'), ('Hindi', 'Hindi')], default=0, max_length=28),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='guideregistermodel',
            name='locations',
        ),
        migrations.AddField(
            model_name='guideregistermodel',
            name='locations',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Everest Base Camp', 'Everest Base Camp'), ('Annapurna Base Camp', 'Annapurna Base Camp')], default=True, max_length=57),
            preserve_default=False,
        ),
    ]
