# Generated by Django 2.2 on 2020-02-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HireModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=50)),
                ('pick_date', models.DateField()),
                ('full_address', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=14)),
                ('tour', models.CharField(choices=[('shared', 'shared'), ('private', 'private')], max_length=20)),
            ],
        ),
    ]
