# Generated by Django 2.2 on 2020-02-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiremodel',
            name='tour',
            field=models.CharField(choices=[('shared', 'shared'), ('private', 'private')], default='shared', max_length=20),
        ),
    ]
